<a href="https://colab.research.google.com/github/archamohan343-hue/ICT-/blob/main/internshipday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for num in range(5) :
  print(num)

0
1
2
3
4


In [ ]:
for num in range(1,25) :
  print(num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [ ]:
for i in range(5):
  print("welcome all")

welcome all
welcome all
welcome all
welcome all
welcome all


In [ ]:
grocery_list=["apples","milk","bread","peanut butteer","yougurt"]
print("items to buy:")
for items in grocery_list:
  print(items)

items to buy:
apples
milk
bread
peanut butteer
yougurt


In [ ]:
grocery_list=["apples","milk","bread","peanut butteer","yougurt"]
new_list=["juice","pencils","cheese","eggs","milk","pens"]

for item in new_list:
  if item in grocery_list:
    print(f"{item} already in the list")
  else:
    grocery_list.append(item)
    print(f"{item} added to the list" )

print("updated list:")
print(grocery_list)

juice added to the list
pencils added to the list
cheese added to the list
eggs added to the list
milk already in the list
pens added to the list
updated list:
['apples', 'milk', 'bread', 'peanut butteer', 'yougurt', 'juice', 'pencils', 'cheese', 'eggs', 'pens']


In [ ]:
expenses_sevendays=[5550,300,1500,280,480]
total=0
for expenese in expenses_sevendays:
  total+=expense
  print("total:",total)


total: 5550
total: 11100
total: 16650
total: 22200
total: 27750


In [ ]:
numbers=["9876543210","6788","4893209","0908878767645"]
print(numbers)
for num in numbers:
  if len(num)==10:
    print(num,"This number is valid")
  else:
      print(num,"This number is invalid")

['9876543210', '6788', '4893209', '0908878767645']
9876543210 This number is valid
6788 This number is invalid
4893209 This number is invalid
0908878767645 This number is invalid


In [ ]:
count=1
while count<10:
  print(f"counting{count}")
  count+=1

print("loop completed")

counting1
counting2
counting3
counting4
counting5
counting6
counting7
counting8
counting9
loop completed


In [ ]:
amount=int(input("Enter your saving amount"))
total=0

while amount!=0:
   total+=amount
   amount=int(input("Enter the amount to be saved"))

print("total is",total)


Enter your saving amount3000
Enter the amount to be saved24000
Enter the amount to be saved558
Enter the amount to be saved0
total is 27558


In [ ]:
cart={"shoes":2000,"bag":3500,"watch":1900,"glasses":1200}
C


this shoes can be purchased
thisbag is expensive
this watch can be purchased
this glasses can be purchased


In [ ]:
cart={"shoes":2000,"bag":3500,"watch":1900,"glasses":1200}



In [ ]:
def greet():
  print("Hi, welcome to the session")

greet()
greet()

Hi, welcome to the session
Hi, welcome to the session


In [ ]:
def greet(name):
  print(f"Hi {name}, welcome to the session")

greet("Baiga")
greet("ponnu")

Hi Baiga, welcome to the session
Hi ponnu, welcome to the session


In [ ]:
def send_gift(recipient,gift="roses"):
  print(f"sending {gift} to {recipient}")

send_gift("Maya","iPhone")
send_gift("Midhuna","bag")
send_gift("Balu","a shirt")
send_gift("Appu","Kunju")
send_gift("Ardra")

sending iPhone to Maya
sending bag to Midhuna
sending a shirt to Balu
sending Kunju to Appu
sending roses to Ardra


In [ ]:
def add_ten(number):
  return (number+10)

add_ten(3) * 29

377

In [ ]:
def calculate_total_bill(item_price):
  platformfee=5
  deliverycharge=80
  subtotal=sum(item_price)
  subtotal+=platformfee
  subtotal+=deliverycharge
  return subtotal

item_price=[100,200,300,800]
subtotal= calculate_total_bill(item_price)
if subtotal>1000:
  reward=200
elif subtotal>500:
  reward=50
else:
  reward=0


print(f"Your subtotal is,{subtotal} and reward is {reward} ")


Your subtotal is,1485 and reward is 200 


# **Numpy**

In [ ]:
import numpy as np

In [ ]:
x= np.array([1,2,3,4,5])
x

array([1,2,3,4,5])


NameError: name 'array' is not defined

In [ ]:
y= np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.sum(y)

np.int64(78)

In [ ]:
np.max(y)

np.int64(12)

In [ ]:
np.min(y)

np.int64(1)

In [ ]:
np.mean(y)

np.float64(6.5)

In [ ]:
np.shape(y)

(4, 3)

In [ ]:
np.ndim(y)

2

In [ ]:
np.size(y)

12

In [ ]:
np.random.randint(1,50,size=(4,3))

array([[10, 20,  5],
       [46, 11, 37],
       [48, 30, 43],
       [46, 29, 12]])

In [ ]:
x=np.array([0,1,2,3,4])
y=np.array([5.5,-6.5,-4,7.5,8])

np.add(x,y)


array([ 5.5, -5.5, -2. , 10.5, 12. ])

In [ ]:
np.add(x,y)

array([ 5.5, -5.5, -2. , 10.5, 12. ])

In [ ]:
np.subtract(x,y)

array([-5.5,  7.5,  6. , -4.5, -4. ])

In [ ]:
np.multiply(x,y)

array([ 0. , -6.5, -8. , 22.5, 32. ])

In [ ]:
np.divide(x,y)

array([ 0.        , -0.15384615, -0.5       ,  0.4       ,  0.5       ])

In [ ]:
np.abs(x,y)

array([0., 1., 2., 3., 4.])

In [ ]:
np.sqrt(x,y)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sin(x,y)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.tan(x,y)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [ ]:
np.dot(x,y)

np.float64(1.390973498307341)

PANDAS

In [ ]:
import pandas as pd
data = pd.read_csv("/content/pandas-practice-data.csv")
data.head()

,Duration,Pulse,Maxpulse,Calories
0,60,110,130,409.1
1,60,117,145,479.0
2,60,103,135,340.0
3,45,109,175,282.4
4,45,117,148,406.0


In [ ]:
data.tail()

,Duration,Pulse,Maxpulse,Calories
164,60,105,140,290.8
165,60,110,145,300.0
166,60,115,145,310.2
167,75,120,150,320.4
168,75,125,150,330.4


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
data.describe()

,Duration,Pulse,Maxpulse,Calories
count,169.000000,169.000000,169.000000,164.000000
mean,63.846154,107.461538,134.047337,375.790244
std,42.299949,14.510259,16.450434,266.379919
min,15.000000,80.000000,100.000000,50.300000
25%,45.000000,100.000000,124.000000,250.925000
50%,60.000000,105.000000,131.000000,318.600000
75%,60.000000,111.000000,141.000000,387.600000
max,300.000000,159.000000,184.000000,1860.400000


In [ ]:
data.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
data['Duration']

,Duration
0,60
1,60
2,60
3,45
4,45
...,...
164,60
165,60
166,60
167,75


In [ ]:
data.nunique()

,0
Duration,16
Pulse,47
Maxpulse,57
Calories,142


In [ ]:
data['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
data['Duration'].value_counts()

,count
Duration,
60,79
45,35
30,16
20,9
90,8
150,4
180,3
120,3
75,2


In [ ]:
data.isna().sum()

,0
Duration,0
Pulse,0
Maxpulse,0
Calories,5


In [ ]:
new_data = data.dropna()
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  164 non-null    int64  
 1   Pulse     164 non-null    int64  
 2   Maxpulse  164 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB


In [ ]:
cal_mean=data['Calories'].mean()
new_data1=data["Calories"].fillna(cal_mean)
new_data1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 169 entries, 0 to 168
Series name: Calories
Non-Null Count  Dtype  
--------------  -----  
169 non-null    float64
dtypes: float64(1)
memory usage: 1.4 KB


In [ ]:
data['caloriesPerMinute']= data['Calories']/data['Duration']
data

,Duration,Pulse,Maxpulse,Calories,caloriesPerMinute
0,60,110,130,409.1,6.818333
1,60,117,145,479.0,7.983333
2,60,103,135,340.0,5.666667
3,45,109,175,282.4,6.275556
4,45,117,148,406.0,9.022222
...,...,...,...,...,...
164,60,105,140,290.8,4.846667
165,60,110,145,300.0,5.000000
166,60,115,145,310.2,5.170000
167,75,120,150,320.4,4.272000


In [ ]:
import pandas as pd
data=pd.read_csv("/content/titanic_dataset.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [ ]:
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data['Name']

,Name
0,"Braund, Mr. Owen Harris"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,"Heikkinen, Miss. Laina"
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,"Allen, Mr. William Henry"
...,...
886,"Montvila, Rev. Juozas"
887,"Graham, Miss. Margaret Edith"
888,"Johnston, Miss. Catherine Helen ""Carrie"""
889,"Behr, Mr. Karl Howell"


In [ ]:
data.nunique()

,0
PassengerId,891
Survived,2
Pclass,3
Name,891
Sex,2
Age,88
SibSp,7
Parch,7
Ticket,681
Fare,248


In [ ]:
data['Name'].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar 

In [ ]:
data['Pclass'].value_counts()

,count
Pclass,
3,491
1,216
2,184


In [ ]:
data.isna().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [ ]:
 data['Cabin'].dropna()

,Cabin
1,C85
3,C123
6,E46
10,G6
11,C103
...,...
871,D35
872,B51 B53 B55
879,C50
887,B42


In [ ]:
age_mean=data['Age'].mean()
new_data1=data["Age"].fillna(age_mean)
new_data1

,Age
0,22.000000
1,38.000000
2,26.000000
3,35.000000
4,35.000000
...,...
886,27.000000
887,19.000000
888,29.699118
889,26.000000
